# Generated by Django 4.0.1 on 2022-02-04 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_core', '0002_sharecount_expense_calculation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('group_id', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ShareCount',
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot_core.expensegroup'),
            preserve_default=False,
        ),
    ]
