# Generated by Django 4.0.1 on 2022-02-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_core', '0004_messagelog_user_group_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('group_id', models.CharField(max_length=255, unique=True)),
                ('members_count', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
